### PR TITLE
Add seeding

### PR DESCRIPTION
**Pull request by pfistfl**

### CODE REVIEW

**Comment by pfistfl** [comment]
This enriches the initial config with defaults defined in the problem
Should seeding be a parameter or just always in?

**Comment by PGijsbers** [comment]
I'm not entirely sure what you mean, sorry. I'm not entirely sure I understand the code changes exactly either 😅 Will "problem.benchmarks" define a list of symbolic defaults as string?

**Comment by pfistfl** [comment]
Benchmarks currently is the set of fixed configs we compare against.
This would allow us to put either these or a list of other defaults into
the initial population

PGijsbers <notifications@github.com> schrieb am Mo., 23. März 2020, 17:42:

**Comment by PGijsbers** [comment]
How embarrassing 🤦‍♂

**Pull request merged**
